include = ["src/*.py", "examples/*.py", "examples/*.ipynb", "tests/*.py"]
line-length = 88
target-version = "py312"

[lint]
select = ["ALL"]
ignore = ["D211", "COM819", "ISC001", "D213", "D203", "FA102"]

[format]
docstring-code-format = true
